<template>
  <div class="inline-flex ml-3 rounded-md shadow">
    <a
      target="_blank"
      href="https://github.com/web2033/vite-vue3-tailwind-starter"
      class="
        inline-flex
        items-center
        justify-center
        px-5
        py-3
        text-base
        font-medium
        leading-6
        text-indigo-600
        transition
        duration-150
        ease-in-out
        bg-white
        border border-transparent
        rounded-md
        hover:text-indigo-500
        focus:outline-none
      "
      >Learn more</a
    >
    <button
      class="
        bg-pink-500
        text-white
        active:bg-pink-600
        font-bold
        uppercase
        text-sm
        px-6
        py-3
        rounded-full
        shadow
        hover:shadow-lg
        outline-none
        focus:outline-none
        mr-1
        mb-1
        ease-linear
        transition-all
        duration-150
      "
      type="button"
    >
      <i class="fas fa-heart"></i> Regular
    </button>
  </div>
</template>
